
name: PHP Continuous integration

on:
  push

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --ignore-platform-reqs
        
    - name: Run unit tests, Code Sniffer,Mess Detector
      run: vendor/bin/grumphp run
